const names = [
  'Aldeco Fabric',
  'Alhambra Fabric',
  'Altura',
  'Arteriors Home Lighting',
  'Artifacts International',
  'Atelier Purcell',
  'B. Berger Fabrics',
  'Bailey & Griffin Fabrics',
  'Baker Lifestyle Fabrics',
  'Baker Lifestyle Wallpaper',
  'Beacon Hill Fabrics',
  'Boris Kroll Fabric',
  'Brentano Fabrics',
  'Brunschwig & Fils Fabrics',
  'Brunschwig & Fils Wallpaper',
  'Calvin Fabrics',
  'Calvin Wallpaper',
  'Castel Maison Fabrics',
  'Charles Loomis Lighting',
  'Charlotte Fabrics',
  'Christian Fischbacher Fabric',
  'Christian Fischbacher Wallpaper',
  'Christopher Farr Fabrics',
  'Christopher Farr Rugs',
  'Christopher Farr Wallpaper',
  'Clarence House Fabrics',
  'Clarence House Wallpaper',
  'Clarke & Clarke Fabrics',
  'Clarke & Clarke Wallpaper',
  'Cole & Son Wallpaper',
  'Cole & Son Fabrics',
  'Colony Fabrics',
  'Decorative Crafts Furniture',
  'Decorative Crafts Lighting',
  'Designer’s Guild Fabrics',
  'Designer’s Guild Wallpaper',
  'Duralee Fabrics',
  'Duralee Furniture',
  'Fabricut Fabrics',
  'Fabricut Wallpaper',
  'Friedman Brothers Mirrors',
  'Gaston Y Daniela Fabrics',
  'Gaston Y Daniela Wallpaper',
  'GP & J Baker Fabrics',
  'GP & J Baker Wallpaper',
  'Grange',
  'Grey Watkins Fabrics',
  'Groundworks Fabrics',
  'Groundworks Wallpaper',
  'Highland Court Fabrics',
  'Hilliard Lighting',
  'Ironware International Furniture',
  'Ironware International Lighting',
  'Jasper Fabrics',
  'Jasper Furniture',
  'Jasper Lighting',
  'Jasper Wallpaper',
  'Kravet',
  'Kravet Curated',
  'Kravet Curated Accessories',
  'Kravet Curated Lighting',
  'Kravet Fabrics',
  'Kravet Furniture',
  'Kravet Wallpaper',
  'Kravet Basics Fabrics',
  'Kravet Contract Fabrics',
  'Kravet Couture Fabrics',
  'Kravet Smart Fabrics',
  'Kravet Rugs',
  'Laura Ashley Fabrics',
  'Lelievre Fabric',
  'Lelievre Wallpaper',
  'Lee Jofa',
  'Lee Jofa Fabrics',
  'Lee Jofa Wallpaper',
  'Louis J. Solomon',
  'Lulu DK Fabrics',
  'Lorca Fabrics',
  'Marian Jamieson Lighting',
  'Matthew Williamson Fabrics',
  'Matthew Williamson Wallpaper',
  'Maya Romanoff Wallpaper',
  'Michael S. Smith',
  'Mimi London',
  'Missoni Home Wallpaper',
  'Mulberry Home Fabrics',
  'Mulberry Home Wallpaper',
  'Nicolette Mayer Fabric',
  'Nicolette Mayer Wallpaper',
  'Nina Campbell Fabrics',
  'Nina Campbell Wallpaper',
  'O’Henry House',
  'Old World Weavers Fabrics',
  'Opuzen Fabrics',
  'Osborne & Little Fabrics',
  'Osborne & Little Wallpaper',
  'Peter Dunham Fabrics',
  'Phoenix Day Lighting',
  'Pindler Fabrics',
  'Ralph Lauren Fabrics',
  'Ralph Lauren Wallpaper',
  'Robert James Collection',
  'Robert Allen Fabrics',
  'Robert Allen @Home Fabrics',
  'Robert Allen Contract Fabrics',
  'Ryan Jackson',
  'Sandberg Wallpaper',
  'Scalamandre Fabrics',
  'Scalamandre Wallpaper',
  'Schumacher Fabrics',
  'Schumacher Wallpaper',
  'Schumacher Furniture',
  'Stroheim Fabrics',
  'Stroheim Wallpaper',
  'Suburban Home Fabrics',
  'S. Harris Fabrics',
  'Ted Boerner',
  'Trend Fabrics',
  'Threads Fabrics',
  'Threads Wallpaper',
  'Victoria Hagan Furniture',
  'Vervain Fabrics',
  'Victoria Hagan Fabrics',
  'Winfield Thybony Wallpaper',
]

const queries = names.map((name) =>
  name
    .toLowerCase()
    .replace('&', 'and')
    .replace('@', '')
    .replace('.', '')
    .split(' ')
    .join('+')
)

module.exports = names.map((name, i) => ({ name, q: queries[i] }))
